name: practice
favicon: null
layout_spectrum: 0.87832
typography_spectrum: 0.79155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f9'
    - '#76777c'
    - '#441410'
    - '#c7bdbf'
    - '#d94960'
  brandStrength: 0.9994896317366511
  lightness: 0.7307702817488462
  saturation: 0.8125
  rhythmicContrast: 0.939390602055937
purpose: []
